# config.yaml
required_columns: ['ts', 'Open', 'High', 'Low', 'Close', 'Volume']
price_columns: ['Open', 'High', 'Low', 'Close', 'Volume']
ma_period: 14
initial_cap: 1000000
fee_rate: 0.001
stop_loss_pct: 0.04
take_profit_pct: 0.05
threshold: 0.001
entry_range: 5
entry_time: '09:06'
exit_times: ['11:00', '13:00', '13:30'] 
batch_size: 10
num_processes: 4
trading_days_per_year: 252
risk_free_rate: 0.02
# start_time : '2021-10-14 09:06:00'
# end_time : '2024-10-14 13:30:00'


